stages:
    - build:toDEV-HMS
    - deploy:toDEV-HMS
  
build_app_for_DEV_HMS:
  stage: build:toDEV-HMS
  image: trion/ng-cli:7.2.3
  before_script:
    - npm ci
  script:
    - node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build --configuration=dev-hms
  artifacts:
    paths:
      - dist/
      - backup-hms-dev/
  only:
    - DEVHMS

deploy_to_DEV_HMS:
  image: alpine
  stage: deploy:toDEV-HMS
  dependencies:
    - build_app_for_DEV_HMS  
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" >> /root/.ssh/id_dsa
    - chmod 600 /root/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
    - apk add --no-cache python py-pip
    - pip install awscli
    - aws s3 sync s3://dev-ayo-hms "$USER"@"$TARGET_SERVER":/var/www/backup-dev-ayo-hms/ --delete
    - aws s3 sync dist/ayo-principal/ s3://dev-ayo-hms/ --delete
  only:
    - DEVHMS
  