export const sample = {
  "status": "success",
  "data": {
    "id": 5,
    "name": "Misi Base response 5",
    "trade_creator_id": 261,
    "trade_audience_group_id": 1,
    "start_date": "2020-06-25",
    "end_date": "2020-06-30",
    "total_budget": 10000000,
    "current_week": 4,
    "total_week": 50,
    "status": "publish",
    "created_at": "2020-06-25 15:57:36",
    "updated_at": "2020-06-25 15:57:36",
    "trade_creator_name": "Trade 3 Agustus 2020",
    "trade_audience_group_name": "DUMMY TEST 1",
    "actions": [
      {
        "id": 4,
        "component_id": 1,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "misi 1",
        "type": "mission",
        "attribute": {
          "task_template_id": 279,
          "start_date": "2020-06-25",
          "end_date": "2020-06-30",
          "verification_type": "retailer",
          "coin_submission": 100,
          "coin_verification": 50
        },
        // "previous_step_component": null,
        "next_step_component": 2,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 5,
        "component_id": 2,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "split decision",
        "type": "decision",
        "attribute": null,
        // "previous_step_component": 1,
        "next_step_component": null,
        "next_step_component_yes": 3,
        "next_step_component_no": 4,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 6,
        "component_id": 3,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "earn coin",
        "type": "coin",
        "attribute": {
          "total_coin": 100
        },
        // "previous_step_component": 2,
        "next_step_component": 5,
        "decision_type": "yes",
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 7,
        "component_id": 4,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "waiting time",
        "type": "time",
        "attribute": {
          "time": 1,
          "type": "week"
        },
        // "previous_step_component": 2,
        "next_step_component": 6,
        "decision_type": "no",
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 8,
        "component_id": 5,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "mission 2",
        "type": "mission",
        "attribute": {
          "task_template_id": 279,
          "start_date": "2020-06-25",
          "end_date": "2020-06-30",
          "verification_type": "principal",
          "coin_submission": 100,
          "coin_verification": 50
        },
        // "previous_step_component": 3,
        "next_step_component": 7,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 9,
        "component_id": 6,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "push notification",
        "type": "notification",
        "attribute": null,
        // "previous_step_component": 4,
        "next_step_component": 8,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 10,
        "component_id": 7,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "split decision",
        "type": "decision",
        "attribute": null,
        // "previous_step_component": 5,
        "next_step_component": null,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 11,
        "component_id": 8,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "split decision",
        "type": "decision",
        "attribute": null,
        "previous_step_component": 6,
        "next_step_component": null,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 12,
        "component_id": 9,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "split decision",
        "type": "decision",
        "attribute": null,
        "previous_step_component": 7,
        "next_step_component": 3,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 13,
        "component_id": 10,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "finish",
        "type": "finish",
        "attribute": null,
        "previous_step_component": 8,
        "next_step_component": null,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 14,
        "component_id": 11,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "earn coin",
        "type": "coin",
        "attribute": null,
        "previous_step_component": 7,
        "next_step_component": 13,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 15,
        "component_id": 12,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "finish",
        "type": "finish",
        "attribute": null,
        "previous_step_component": 7,
        "next_step_component": null,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      },
      {
        "id": 16,
        "component_id": 13,
        "task_sequencing_management_id": 5,
        "task_template_id": null,
        "name": "finish",
        "type": "finish",
        "attribute": null,
        "previous_step_component": 11,
        "next_step_component": null,
        "decision_type": null,
        "created_at": "2020-06-25 15:57:36",
        "updated_at": "2020-06-25 15:57:36"
      }
    ]
  }
}